### ISSUE TITLE
ssh-keypath attribute in EC2 Node Source configuration

### ISSUE THREAD

**Issue by chobbs** [rundeck/docs#1040]
**Describe the bug**

A prospect following the documentation for configuring the Amazon EC2 Node Source used the `ssh-keypath.default` attribute example in the docs for the **Mapping Params** field. However, this attribute applies to local file keys which is not mentioned in the setup. The prospect assumed this example attribute would work using the built-in key storage path and lost days based on the error message returned when trying to execute.

Looking for options to possibly guide prospects to better understand so they don't get lost.

Suggestions:
- multiple entries showing attributes for local and key-store access
- change the `keys/us-west-1-privKey` example entry to something that represents a local file path `/var/lib/rundeck/.ssh/us-west-1-privKey` 

_Screen Shot_

<img width="975" alt="Screen Shot 2022-07-28 at 3 45 10 PM" src="https://user-images.githubusercontent.com/950997/181649737-beabc877-e83f-4cee-b72a-c75b47e448ec.png">

**Source page**

Amazon EC2 Node Source :
[https://docs.rundeck.com/docs/manual/projects/resource-model-sources/aws.html#configuring](url)

**Comment by fdevans** [comment]
This setting is covered on the Key-Storage page here:
https://docs.rundeck.com/docs/manual/key-storage/key-storage.html#using-keys-via-rundeck-node-executors

`The default and typical usage is to use a private key stored on the local file system specified via the ssh-keypath attribute.`

I also updated the description on https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#profile

It does not need further clarification on the AWS page as everywhere it's used on the docs site it's a local file.
