### ISSUE TITLE
Documentation bug - Database JDBC Driver Jar File locations

### ISSUE THREAD

**Issue by frachel** [rundeck/docs#106]
The documentation for different databases (SQL Server and Oracle) in this case are at odds with each other as to where to put the JDBC JAR file, and neither is correct if you are using the RPM (or DEB) installation method.

SQL Server page says to put it here: Place it under %RDECK_BASE%
Oracle page says to put it here: Copy the downloaded file ojdbc7.jar to the $RDECK_BASE/server/lib

There is no 'server/lib' directory anywhere.  RDECK_BASE seems to end up as /var/lib/rundeck, which has no "server" subdirectory.

You can put the JAR in "/var/lib/rundeck/exp/webapp/WEB-INF/lib", or modify the rundeckd script and point to a more central location. What's the preferred method? I'm not a fan of either of them.. but at a minimum I think the docs should be consistent and correct.

**Comment by shehzadshaikh** [comment]
I have run into similar problem, not able to find the jdbc jar location to put my postgreSQL jar. Any help in this regard would be much appreciated!

**Comment by frachel** [comment]
For now, putting it in "/var/lib/rundeck/exp/webapp/WEB-INF/lib" works for me, I just don't like it there. Originally I modified the "rundeckd" start script and just added it to the classpath, but decided I'd rather not mess with any of the standard files so any rpm upgrade would go smoother.

**Comment by UnicodeTreason** [comment]
The documentation seems to have been updated since this Issue was raised, but /var/lib/rundeck/lib doesnt work as the dir for [sqljdbc_auth.dll](https://docs.rundeck.com/docs/administration/configuration/database/secure_mssql.html)

Is there another dir we need to use for that file or is /var/lib/rundeck/lib just incorrect entirely?

**Comment by fdevans** [comment]
@JustinAddams That folder should be the right one.  If you're still having issues open an issue on the rundeck/rundeck repo or if you are using Enterprise reach out to our Support Team and they can help you.
