### ISSUE TITLE
deploy updated 3.0.x branch for release 3.0.5 docs

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/docs#110]
My PRs are not getting to "docs" they are in "3.0.x" path:
merge: https://github.com/rundeck/docs/commit/d0700cc41ab6108e27b97ae4af2f53aaec675f14
docs for latest version: https://rundeck.org/docs/administration/configuration/database/oracle.html
my PR is in here: https://rundeck.org/3.0.x/administration/configuration/database/oracle.html

**Comment by jessemarple** [comment]
This issue is not applicable to current version. If the issue does not appear to be resolved or no longer applicable please re-open.
