### ISSUE TITLE
Windows service throws error for the missing license

### ISSUE THREAD

**Issue by ebrucucen** [rundeck/docs#113]
I have installed rundeckpro-windows-3.0.6-20180917, installed service, but it fails to start. 
Is there any place I can put the license as I can't get to the next step for UI?

```
2018-09-19 15:33:27.409  INFO --- [           main] rundeckapp.BootStrap                     : Rundeck startup finished in 1164ms
Grails application running at http://xyz:4440 in environment: production
2018-09-19 15:33:35.778 ERROR --- [pool-2-thread-1] rundeckpro.license.LicenseService        : RundeckPRO License: Not Installed
```

**Comment by gschueler** [comment]
Hi @ebrucucen If you have questions about Rundeck Pro, you should file a support request via our support portal at https://support.rundeck.com

There is also information here about installing the License Key file: http://support.rundeck.com/customer/en/portal/articles/2827074-install-license-key-on-rundeck-pro

Rundeck Pro should start even without a license key.  If you have other problems starting rundeck, you can contact support as Pro subscriber or Trial user, or you can post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!

You can also get more information and links to other ways to get help here: http://rundeck.org/help.html
