### ISSUE TITLE
Documentation bug - project setup

### ISSUE THREAD

**Issue by kramos** [rundeck/docs#115]
On here:
https://rundeck.org/docs/manual/getting-started.html#project-setup

The link in this sentence is broken:
"The Project setup chapter in the Administrator guide will show you how to learn to add Nodes, automate the creation and maintenance of Rundeck projects."

This doesn't exist:
https://rundeck.org/docs/administration/configuration/project-setup.html

I'm not sure which real page it's supposed to point to.

**Comment by gschueler** [comment]
Thanks for the report!
