### ISSUE TITLE
multiauth example

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/docs#12]
http://rundeck.org/docs/administration/authenticating-users.html#multiple-authentication-modules
In the multiauth example, line 24 says "org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule" it should be "org.eclipse.jetty.jaas.spi.PropertyFileLoginModule" (without the 'plus'), if not, realm users won't be able to login.

**Comment by martinbydefault** [comment]
This is related to this change: https://rundeck.org/docs/upgrading/upgrade-guide-2.x.html#jetty-embedded-server-was-upgraded-to-9.0.x

I can submit a PR with this change.
