### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by wkk1020** [rundeck/docs#121]
URL: https://rundeck.org/docs/administration/security/authenticating-users.html#ldap

Under the LDAP -> Configuration -> Step2: Specify login module section:

**************************************************************************************************
For the RPM/Deb installation: the absolute path to the JAAS config file must be specified with the java.security.auth.login.config property.

Declare RDECK_JVM_OPTS in /etc/sysconfig/rundeckd (rpm) or /etc/default/rundeckd (deb):

RDECK_JVM_OPTS="-Drundeck.jaaslogin=true \ 
       -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf \
       -Dloginmodule.name=RDpropertyfilelogin"
**************************************************************************************************

Should the RDECK_JVM_OPTS be something like this? (assuming the "ldap" is configured in /etc/rundeck/jaas-ldap.conf)

RDECK_JVM_OPTS="-Drundeck.jaaslogin=true \ 
       -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
       -Dloginmodule.name=ldap"

**Comment by gschueler** [comment]
thanks, yes i think it should be `jaas-ldap.conf`
