### ISSUE TITLE
Cannot use my js code on the "Edit Node" page

### ISSUE THREAD

**Issue by rjeutski** [rundeck/docs#122]
I have java Rundeck UI plugin and i want to use my js code on the "Edit Nodes" page but it is not available on this page and it is worked on other pages.
In the docks there is no this page in the list of available pages which can load UI plugins. https://rundeck.org/docs/developer/ui-plugins.html#behavior
Is any way to use my js code on this page? Thank you in advance.
![untitled](https://user-images.githubusercontent.com/3263552/46296415-9e85bb80-c59a-11e8-9897-f70708b5e92d.jpg)

**Comment by gschueler** [comment]
Please open an issue in the rundeck/rundeck project: https://github.com/rundeck/rundeck/issues

I think this is a bug
