### ISSUE TITLE
webhook update mandatory id fields required

### ISSUE THREAD

**Issue by ghost** [rundeck/docs#1309]
The documentation specifies that to update a webhook, these are the Required Fields:
id
project
Along with the required fields you may send only the fields you want to update.

But you also need to add the roles field in the API call, Not sure why roles are mandatory and are not specified in the rundeck documentation.

**Source page**
https://docs.rundeck.com/docs/api/rundeck-api.html#update-a-webhook

**Comment by fdevans** [comment]
Thanks for finding this @Idolcemascolo-cs .  It will be updated on our next site refresh.
