### ISSUE TITLE
Links broken on API chapter

### ISSUE THREAD

**Issue by brmdias** [rundeck/docs#1395]
**Describe the bug**
On Result Data plugin page, API chapter, links pointing to related API calls are broken.

**Source page**
[Result Data](https://docs.rundeck.com/docs/manual/execution-lifecycle/result-data.html#api)

**Comment by fdevans** [comment]
What version are you on?  I think we fixed this in a recent version.

**Comment by fdevans** [comment]
nvm... fixed
