### ISSUE TITLE
Documentation bug in file manpages/man5/aclpolicy-v10.md

### ISSUE THREAD

**Issue by Ele-M-ent** [rundeck/docs#146]
Your documentation doesn't work in my rundeck node

I'm trying to simply create an aclpolicy for an user that need to run a specific job, but it doesn't work by following your documentation..

**my testuser.aclpolicy file** 

~~~.yaml
description: restrict access to job testvpo
context:
  project: 'myproject'
for:
  resource:
     - equals:
        kind: job
       allow: '*'
  project
     - equals:
         name: 'myproject'
       allow: [read]
  job:
     - equals:
         name: 'testvpo'
       allow: '*'
by:
  username: 'testuser'
~~~

**my realm.properties file**
testuser:MD5:94429081cea507d1fea1b2ccc9611ff1,user

**Comment by gschueler** [comment]
the `project` is missing `:`, but also, the `project:` needs to be within a application context.

You can try these policies:

~~~.yaml
description: restrict access to job testvpo
context:
  project: 'myproject'
for:
  resource:
     - equals:
        kind: job
       allow: '*'
  job:
     - equals:
         name: 'testvpo'
       allow: '*'
by:
  username: 'testuser'

---

description: view access to a single project
context:
  application: 'rundeck'
for:
  project:
    - equals:
        name: 'myproject'
      allow: [read] 
by:
  username: 'testuser'
~~~

**Comment by gschueler** [comment]
Please post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!
