### ISSUE TITLE
Ruleset Workflow Strategy Plugin cannot be accessed from WorkFlow Strategy 

### ISSUE THREAD

**Issue by skywalke34** [rundeck/docs#166]
Ruleset Workflow Strategy needs to be a link underneath https://rundeck.org/docs/manual/workflow-strategies/index.html.. You can get to the Ruleset workflow strategy plugin link from https://rundeck.org/docs/manual/creating-job-workflows.html, but if you link up to manual/workflow-strategies/index.html, you cannot get  back to the Ruleset Workflow Strategy which should be a subtopic.   See Screen Shot below...

May be linked to issue #140 

**Source page**
**This page** https://rundeck.org/docs/manual/workflow-strategies/ruleset-workflow-strategy-plugin.html
cannot be accessed from
**this page:** https://rundeck.org/docs/manual/workflow-strategies/index.html

![image](https://user-images.githubusercontent.com/11443283/49702310-13d1c600-fbb4-11e8-8567-0bb7d7a90732.png)

**Comment by fdevans** [comment]
We are no longer using the breadcrumb nav shown in the screenshots.  Closing for now.
