### ISSUE TITLE
Useability - API Reference navigation

### ISSUE THREAD

**Issue by skywalke34** [rundeck/docs#167]
API Reference is lacking navigation, and is an opportunity to make research and reference more user friendly.  :)

Example
Scroll down the left hand menu to Resources/Nodes > Listing Resources

Click Listing Resources moves to https://docs.rundeck.com/docs/api/#listing-resources
_Now the only way to navigate back to the top is via the browser back button, or manually scrolling._

![image](https://user-images.githubusercontent.com/11443283/50127654-4a03eb00-022f-11e9-9ff7-bbc42b7361a8.png)

**Source page**
https://docs.rundeck.com/docs/api/#index

**Suggested Enhancement**
Possible scroll bar on far right side to speed vertical navigation
and/or place the left hand menu in a pane that can be navigated separate, and so it doesn't scroll out of the window when viewing API documentation on the right.

**Comment by jessemarple** [comment]
This issue is not applicable to current version. If the issue does not appear to be resolved or no longer applicable please re-open.
