### ISSUE TITLE
Broken Links - Creating Jobs

### ISSUE THREAD

**Issue by skywalke34** [rundeck/docs#174]
**Describe the bug**
3 links are broken on https://docs.rundeck.com/docs/manual/creating-jobs.html.

1. The local link https://docs.rundeck.com/docs/manual/creating-jobs.html#job-options does not exist on this page.  Should link to https://docs.rundeck.com/docs/manual/defining-job-options.html
![image](https://user-images.githubusercontent.com/11443283/50170828-0b614580-02ae-11e9-908e-227bb0044d61.png)

2. There are two links broken for "Git Plugin".   **see screenshots below** 
   a: the first is for the Git **export** https://docs.rundeck.com/docs/manual/scm/scm-git-plugin.html#configuring-git-export
     **The correct link should be:**  https://docs.rundeck.com/3.0.5/administration/projects/scm/git-plugin.html#configuring-git-export

   b: the second is for the Git **import**  https://docs.rundeck.com/docs/manual/scm/scm-git-plugin.html#git-import-configuration
       **The correct link should be:** https://docs.rundeck.com/3.0.5/administration/projects/scm/git-plugin.html#git-import-configuration

**Source page**
https://docs.rundeck.com/docs/manual/creating-jobs.html
**Screen Shot for 2a and 2b**
![image](https://user-images.githubusercontent.com/11443283/50171493-d6ee8900-02af-11e9-8024-f2efbd4007c9.png)

**Comment by gschueler** [comment]
Closing due to massive link fixes patch by @skywalke34 👍
