### ISSUE TITLE
When taking 3.x screenshots, ensure OS language is consistent with documentation language

### ISSUE THREAD

**Issue by plambert** [rundeck/docs#19]
It's easy for images to capture Spanish or other languages from the OS.  For example:

![license-key-gui-3.png](https://github.com/rundeck/docs/blob/3.0.x/figures/license-key-gui-3.png?raw=true)

We'll just want to be sure to use an English-language system to capture the 3.x images; this ticket is to make that easy to remember and track.

**Comment by jessemarple** [comment]
This issue is not applicable to current version. If the issue does not appear to be resolved or no longer applicable please re-open.
