### ISSUE TITLE
Documentation bug in file administration/security/ssl.md

### ISSUE THREAD

**Issue by aujla0991** [rundeck/docs#197]
**Describe the bug**
A clear and concise description of what the documentation issue is.  

URL link needs to be updated: "rundeck-config.properties"

Note: You will still need to modify the grails.serverURL value in [rundeck-config.properties](https://docs.rundeck.com/docs/administration/security/configuration-file-reference.html#rundeck-config.properties) to let Rundeck know how to properly generate absolute URLs.

URL link does not work 

**Source page**
Please include the link or name for the page of the documentation which has the issue.
https://docs.rundeck.com/docs/administration/security/configuring-ssl.html

**Comment by gschueler** [comment]
Thanks! I believe this is fixed in next docs release, snapshot is here: https://docs.rundeck.com/3.0.x/administration/security/configuring-ssl.html
