### ISSUE TITLE
Missing documentation: builtin workflow steps page needs to be filled out

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#198]
**Describe the bug**
Contents of the Builtin Workflow Steps page needs to be filled 

**Source page**

https://docs.rundeck.com/3.0.x/manual/workflow-steps/builtin-workflow-steps.html#job-state-conditional

**Comment by fdevans** [comment]
I believe this is fixed in the current documentation.  Please reopen if there is more to do.
