### ISSUE TITLE
Preset Policy on Remote Execution (PRO)

### ISSUE THREAD

**Issue by ltamaster** [rundeck/docs#203]
**Describe the bug**
`Present` policy on remote execution just allows `config.uuid` settings, which is not defined on docs.

For example, a correct setting for `Preset` policy is:
```
rundeck.clusterMode.remoteExecution.config.activeOnly = true
rundeck.clusterMode.remoteExecution.profiles = Linux
rundeck.clusterMode.remoteExecution.profile.Linux.projects=Example, Test1, Test2
rundeck.clusterMode.remoteExecution.profile.Linux.policy=Preset
 rundeck.clusterMode.remoteExecution.profile.Linux.config.uuid=<UUID1> 
```

**Source page**
https://github.com/rundeck/docs/blob/3.0.x/en/administration/configuration/remote-job-execution.md

**Comment by fdevans** [comment]
Luis, can you give me a bit more context on this so we can make the updates and close it out?
