### ISSUE TITLE
After upgrading to Rundeck 3.0.13 from 2.6.9 Jobs page is loading much slower

### ISSUE THREAD

**Issue by aznkid4ever** [rundeck/docs#214]
After upgrading to Rundeck 3.0.13 from 2.6.9 Jobs page is loading much slower.
We have around 950 jobs in one project. On version 2.6.9 the jobs page took only 2 seconds to load, however after upgrading to 3.0.13 it now takes around 12 seconds to load.

We're noticing this warning in the the service.log after the jobs page takes a long time to load:
2019-02-07 15:35:56.842  WARN --- [ qtp86178665-24] org.eclipse.jetty.http.HttpParser        : URI is too large >8192

This same message doesn't show up on version 2.6.9 service.log

Have tried several things such as adjusting jvm memory in $RDECK_BASE/etc/profile but no luck:
export RDECK_JVM="$RDECK_JVM -Xmx4096m -Xms2048m -XX:MaxPermSize=1024m"

**Comment by ahonor** [comment]
@aznkid4ever what kind of database are you using?

**Comment by aznkid4ever** [comment]
@ahonor I'm using MySQL. I did try running these commands on the database to try to tune it but also had no luck

ALTER TABLE workflow_workflow_step ADD INDEX workflow_commands_id ( workflow_commands_id );
ALTER TABLE workflow_workflow_step ADD INDEX commands_idx ( commands_idx );

**Comment by ahonor** [comment]
Also add

```
create index EXECUTION__DATE_STARTED 							on execution(date_started);
create index EXECUTION__PROJECT_DATE_STARTED					on execution(project,date_started);
create index SCHEDULED_EXECUTION__PROJECT						on scheduled_execution(project);

create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT 		on base_report(class, jc_job_id, ctx_project);
create index EXECUTION__PROJECT__DATE_COMPLETED 				on execution(project, date_completed);
create index EXECUTION__DATE_COMPLETED__SCHEDULED_EXECUTION_ID 	on execution(date_completed, scheduled_execution_id);
create index WORKFLOW_STEP__ID 									on workflow_step(id);
create index WORKFLOW_WORKFLOW_STEP__WORKFLOW_COMMANDS_ID 		on workflow_workflow_step(workflow_commands_id);

create index EXECUTION__PROJECT__DATE_STARTED 					on execution(date_started, status);
create index BASE_REPORT_EXECUTION_ID							on base_report(jc_exec_id);
create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT3 		on base_report(class, ctx_project,jc_job_id,jc_exec_id);
create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT2		on base_report(class, ctx_project,date_completed,date_started);
create index EXECUTION_PROJECT_NAME_DATE_STARTED 				on execution(id,project,date_completed);
```

**Comment by aznkid4ever** [comment]
@ahonor Thanks for that. I ran the commands and created the indexes but unfortunately the issue persists.

**Comment by BilouteMaif** [comment]
Hi,
Any news about that issue ?
I use rundeck 3.1 with mariadb on the same server.
For a poject with 600 jobs, the page load in 8s.
With network's developer tools, there is 8s of waiting time.
Another with 2500 jobs take 20s !

I have to use the parameter "rundeck.gui.paginatejobs.max.per.page=250" but it is not really UX.

Is there any solution ?

**Comment by jessemarple** [comment]
Hi @BilouteMaif & @aznkid4ever,
This repository is related to our documentation. Please feel free to post your question in our community forums or on the rundeck/rundeck repository and our team will get better visibility on it.

Also, we recommend updating to Rundeck 3.2.x as there have been chances specifically with regards to loading the Jobs page faster.
