### ISSUE TITLE
Links moved from Admin menu to side bar not documented

### ISSUE THREAD

**Issue by jtobard** [rundeck/docs#216]
**Describe the bug**
According to https://docs.rundeck.com/docs/administration/maintenance/backup-and-recovery.html#import-an-archive there should be an Import Archive link in the admin menu

Moved from rundeck/rundeck#4517

**Comment by jessemarple** [comment]
This issue is not applicable to current version. If the issue does not appear to be resolved or no longer applicable please re-open.
