### ISSUE TITLE
What is the username and password for the rundeck/rundeck docker image? It says its admin/admin but that does not work 

### ISSUE THREAD

**Issue by mafudge** [rundeck/docs#217]
**Describe the bug**
A clear and concise description of what the documentation issue is.
What is the username and password for the rundeck/rundeck docker image? It says its admin/admin but that does not work 
STEPS TO RECREATE: 

$docker run -it -p 4440:4000 rundeck/rundeck 
http://localhost:4440 

Login in as ????????????

**Source page**
Please include the link or name for the page of the documentation which has the issue.

**Comment by ProTip** [comment]
Hi @mafudge ,

The default credentials are indeed `admin`/`admin` . However Rundeck in the Docker image runs on `http://127.0.0.1:4440` by default. Accessing it on localhost will result in a redirect after clicking login and will appear to not work. You should be able to run the container with `-e RUNDECK_GRAILS_URL=http://localhost:4440` to change this.

I hope this helps. Please post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!

**Comment by sosnus** [comment]
Yeah!
`http://localhost/` not working, but `http://127.0.0.1:4440/` is OK :O 
Docker on WSL2 Ubuntu Windows 11
```
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
```

**Comment by iamumairayub** [comment]
> -e RUNDECK_GRAILS_URL=http://localhost:4440

I ran 

`docker run --rm -it -p 4440:4440 rundeckpro/enterprise:4.17.3 -e RUNDECK_GRAILS_URL=http://localhost:4440
`
and I get 


```
Unrecognized option: -e
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by programster** [comment]
> > -e RUNDECK_GRAILS_URL=http://localhost:4440
> 
> I ran
> 
> `docker run --rm -it -p 4440:4440 rundeckpro/enterprise:4.17.3 -e RUNDECK_GRAILS_URL=http://localhost:4440 ` and I get
> 
> ```
> Unrecognized option: -e
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.
> ```

Try running:

```bash
IMAGE="rundeckpro/enterprise:4.17.3"
VERSION="4.17.3"

docker run \
  -rm \
  -it \
  -p 4440:4440 \
  -e RUNDECK_GRAILS_URL=http://localhost:4440 \
  $IMAGE:$VERSION
```
I'm pretty sure the environment variables (`-e`) need to be specified *before* you specify the docker image. Everything that comes *after* the docker image is for a command you wish to run on startup, overriding the default command (which you shouldn't need to do).
