### ISSUE TITLE
Documentation bug in file api/rundeck-api.md

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#219]
**Describe the bug**

Bulk Job Delete API describes using `DELETE` method, but this does not work with a request body, only using URL parameters with no body.

The documentation should be fixed and clarify usage of `DELETE` method.

**Source page**

https://docs.rundeck.com/docs/api/index.html#bulk-job-delete

original issue:

https://github.com/rundeck/rundeck/issues/4557

**Comment by fdevans** [comment]
We'd either have to duplicate all the examples or we can remove the `DELETE /api/5/jobs/delete` line and encourage the use of the POST method.

If we want to leave the `DELETE /api/5/jobs/delete` in I'd need a little bit of guidance on example usage.
