### ISSUE TITLE
AWS Installation should link from Administrator Guide > Installation

### ISSUE THREAD

**Issue by skywalke34** [rundeck/docs#220]
**Describe the bug**
Anyone looking for Installation instructions for AWS would expect to find it under Administrator Guide > Installation.   
Was only able to find it by searching, and only then found it under Administrator Guide > Rundeck Enterprise... 
**Then scroll to the bottom of the page**
Find "Sections" (_at the bottom of the page_) click on Cloud Deployment > AWS > 

**Source page**
https://docs.rundeck.com/docs/administration/install/index.html
https://docs.rundeck.com/docs/administration/cluster/cloud/aws.html

![image](https://user-images.githubusercontent.com/11443283/53668764-0f0c3380-3c32-11e9-9bb1-8fe3608b3f34.png)
![image](https://user-images.githubusercontent.com/11443283/53668809-319e4c80-3c32-11e9-8c38-9aba11abf58f.png)
![image](https://user-images.githubusercontent.com/11443283/53668874-6a3e2600-3c32-11e9-9716-302f75faf348.png)

**Comment by ProTip** [comment]
Installation is currently almost exclusively focused on how to obtain and install our distribution packages of `deb`, `rpm`, `war`, and `docker`. These are infrastructure provider agnostic instructions.

The AWS page contains a combination of configuration and AWS _reference architecture_. Currently we have an administration top-level section for configuration; would it make sense to add a reference architecture/deployment section directly under `Administrator Guide`?

**Comment by skywalke34** [comment]
Yes, absolutely would make sense!  :)   I can't help but think infrastructure _before_  I think about the steps for actually installing Rundeck.   _What size server?  How much storage and what types.  What are the performance characteristics. **What other things do I need to think about **before** installing Rundeck that will save me pain & time of having to reconfigure something **after* installing Rundeck.**_
 
That said, I don't know that the AWS info has to _move_, but maybe just adding links in that Administrator Guide to the architecture/deployment info.   It just needs to be easier to find for new-to-installing-Rundeck admins, especially if they are also part of a cloud-migration caravan.  :)

Want me to add the links for review?
