### ISSUE TITLE
Please add documentation on how to reset rundeck login credentials

### ISSUE THREAD

**Issue by JeanMcCallum** [rundeck/docs#236]
**Describe the bug**
I need to reset my rundeck login credentials and am unable to find documentation describing how to do that.

**Source page**
https://docs.rundeck.com/3.0.20/
this is accessed from the "Help" link on the login page

**Comment by jessemarple** [comment]
Please review the content located here:

https://docs.rundeck.com/docs/administration/security/default-users.html
