### ISSUE TITLE
Issue with Rundeck app icons

### ISSUE THREAD

**Issue by Devin-Chaves** [rundeck/docs#237]
**Describe the bug**
In the latest version of rundeck the icons you use, which were formerly text, are now unintuitive and generally meaningless. Accessibility and usability trumps all.

**Comment by gschueler** [comment]
hi, is there a specific issue with the rundeck documentation, or was were you talking about the rundeck application?

**Comment by Devin-Chaves** [comment]
Rundeck application. Thanks

**Comment by gschueler** [comment]
this repo is for the rundeck documentation. if you want to file an issue with rundeck, please do so at https://github.com/rundeck/rundeck/issues
please be specific with the problem you are encountering
