### ISSUE TITLE
Documentation bug in file administration/cluster/loadbalancer/aws-elb.md

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/docs#238]
**Blank page**
A clear and concise description of what the documentation issue is.

https://docs.rundeck.com/docs/administration/cluster/loadbalancer/aws-elb.html
Please include the link or name for the page of the documentation which has the issue.

**Comment by fdevans** [comment]
No details what documentation issue there is.

**Comment by g3nsvrv** [comment]
old issue
