### ISSUE TITLE
Documentation bug in file index.md

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/docs#239]
Outdated paged on the index , Item **4.Rundeck Pro**
[https://docs.rundeck.com/docs/pro/index.html
](https://docs.rundeck.com/docs/pro/index.html
)
Which the new is on 
**Index > 3. Administration Guide > 6. Rundeck Enterprise:**
[https://docs.rundeck.com/docs/administration/cluster/index.html](https://docs.rundeck.com/docs/administration/cluster/index.html
)
A clear and concise description of what the documentation issue is.

[https://docs.rundeck.com/docs/index.html](https://docs.rundeck.com/docs/index.html
)
Please include the link or name for the page of the documentation which has the issue.

**Comment by fdevans** [comment]
@G3NSVRV  What's the issue or bug that needs to be fixed here?

**Comment by g3nsvrv** [comment]
This was an old issue with the docs, before vuepress, this can be closed.
