### ISSUE TITLE
MS SQL Server setup not in the section with the other databases

### ISSUE THREAD

**Issue by frachel** [rundeck/docs#24]
The Administrator Guide has a section "Setting up a RDB Datasource", but it doesn't contain the info for SQL Server (which led me to believe it wasn't supported).

<http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html>

However - in the Installation Guide, in the "Install on Windows" section, there are instructions for using SQL Server

<http://rundeck.org/docs/administration/installation.html#mssql-as-a-backend>

I'd suggest moving the info from the Installation guide to the Administrator Guide.

This is in the version 2.11.4 documentation.

**Comment by gschueler** [comment]
thanks, in 3.0.0 docs we have moved the mssql instructions: http://rundeck.org/docs/administration/configuration/database/ms-sql-server.html
