### ISSUE TITLE
Documentation bug in file manpages/man1/rd.md

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/docs#240]
**Missing content, explanation.**
A clear and concise description of what the documentation issue is.

https://docs.rundeck.com/docs/man1/rd-rundeck-client-cli-tool.html
Please include the link or name for the page of the documentation which has the issue.

**Comment by fdevans** [comment]
No details what the issues is.

**Comment by g3nsvrv** [comment]
old issue
