### ISSUE TITLE
Documentation bug in file manual/workflow-steps/builtin.md

### ISSUE THREAD

**Issue by pwonson** [rundeck/docs#245]
**Describe the bug**
There is no documentation on this page only headings
**Source page**
https://docs.rundeck.com/docs/manual/workflow-steps/builtin-workflow-steps.html#global-variable

**Comment by fdevans** [comment]
Page no longer exists.

**Comment by pam-rundeck** [comment]
The page was moved with the blank headings to here 

https://docs.rundeck.com/docs/manual/workflow-steps/builtin.html#global-variable

**Comment by fdevans** [comment]
This is a fairly large project to document all the steps.  I've added it to our Mandalorian Project plan.

**Comment by pam-rundeck** [comment]
I have documented the global variable here

https://docs.google.com/document/d/1kQBwAD4MXB2fd8k8zx5KobvHKeyZkrtAVsWbEkZT2wQ/edit#

**Comment by fdevans** [comment]
Added Global Variable content.  Thankyou @pam-rundeck
