### ISSUE TITLE
pro: encrypted property plugin documentation is not correct

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#25]
http://rundeck.org/3.0.x-SNAPSHOT/administration/configuration/encryptable-config-properties-pro.html

This documentation is not correct

**Comment by gschueler** [comment]
reference to what should be correct? http://download.rundeck.com/plugins/encrypted-datasource-plugin.html

**Comment by jplassnibatt** [comment]
Also the proper info link is for jar installation, for rpm and deb the grails-plugin-encrypt-datasource-password-x.y.z.jar is in /var/lib/rundeck/exp/webapp/WEB-INF/lib/
And the export RD_ENCRYPTION_DEFAULT_PASSWORD=myDefaultmasterpassword should be defined in /etc/sysconfig/rundeckd (rpm) or /etc/default/rundeckd (deb)

**Comment by sjrd218** [comment]
What is incorrect in the documentation referenced in the first comment? 

The jar file that should be used to initiate the encryption is the rundeck-pro.war itself, not the plugin specific jar.

**Comment by gschueler** [comment]
I'm confused that there are two documented methods to decrypt the password values..

in that snapshot doc it says 

~~~
rundeck.security.ldap.bindPassword=ENC(bbnJmDtx82/NOeUc9ahULGVAH+RdSLG5)
~~~

but in the pro plugin docs it says:

~~~
import static rundeck.codecs.EncryptCodec.decrypt

dataSource.dbCreate="update"
dataSource.url="jdbc:mysql://server/rundeckdb?autoReconnect=true"
dataSource.username="rundeckuser"
dataSource.driverClassName="com.mysql.jdbc.Driver"

//set the password to the result of decrypting
dataSource.password=decrypt 'encryptedpassword'
~~~

**Comment by gschueler** [comment]
(pro plugin docs config is groovy format)

**Comment by fdevans** [comment]
Is any of this still an open issue?

**Comment by chrismcg14** [comment]
@fdevans, this can be closed based off my conversation with @gschueler and @sjrd218
