### ISSUE TITLE
Documentation bug in file index.md

### ISSUE THREAD

**Issue by davepiepkorn** [rundeck/docs#252]
Apologies if I'm addressing in wrong place.  RunDeck will not open other than in text on any browser on my computer.   

**Source page**
https://rundeck.shippersedge.com/menu/home

Below is console result in Devloper Tools in MS Edge, and FF/Chrome have same result also.

SEC7112: Script from https://rundeck.shippersedge.com/assets/jquery-5393bf5931b3c4e7052edeec0d67327b.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/jquery-ui-1a5164fb468e98b907b69ead57230ccc.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/jquery-ui-timepicker-addon-5d3451602f119699d88f688ae667befb.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/perfect-scrollbar-a164e0ac292992c98b8691872ffcb18d.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/bootstrap-all-5a7a806183426a356c9aec640ec1fc13.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/prototype-bundle-96cd287f02a06d0dc9aab56a23ac4b90.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/application-bfd80d79fb89854f491519b58af32783.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/vendor-9a153e4979fa8d6ad0b4784c9a59c827.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/menu/home-e83caee0769d0bf995e70b65d8985a27.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/vendor-9a153e4979fa8d6ad0b4784c9a59c827.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/components/central-7179476701e5756c770a698eee7746c3.js was blocked due to mime type mismatch
home (1,1)

2SCRIPT5009: SCRIPT5009: 'jQuery' is not defined
home (426,3)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/components/version-notification-f96c1bdcdf9d5726e23c89f8ff49afac.js was blocked due to mime type mismatch
home (1,1)

HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
home (974,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/components/motd-161337864f5b73f47e66b4d1d5aad39e.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/components/tour-b75e7028bbf64d02792f94bfafbedde8.js was blocked due to mime type mismatch
home (1,1)

SEC7112: Script from https://rundeck.shippersedge.com/assets/static/components/community-news-notification-36a7cb7c294da0fb6c124e0abda3ff42.js was blocked due to mime type mismatch
home (1,1)

HTML1521: Unexpected "</body>" or end of file. All open elements should be closed before the end of the document.
home (984,1)

**Comment by fdevans** [comment]
@davepiepkorn Sorry this got buried in our Docs project.  If you are still having issues please try on the latest version and if needed open an issue on rundeck/rundeck project and the community might be able to help.
