### ISSUE TITLE
Documentation bug in file administration/install/linux-deb.md

### ISSUE THREAD

**Issue by pwonson** [rundeck/docs#258]
**Describe the bug**
https://download.rundeck.com/3.0.22/index.html
says 'The rundeckpro-cluster package has been renamed to rundeckpro-enterprise.'

The installation page still uses cluster in structions

**Source page**
https://docs.rundeck.com/docs/administration/install/ubuntudebian.html

**Comment by fdevans** [comment]
@pwonson Is this still an issue within the docs?
