### ISSUE TITLE
Documentation bug in file manual/job-options.md

### ISSUE THREAD

**Issue by j3pic** [rundeck/docs#261]
**Describe the bug**
I'm looking for [this page](https://docs.rundeck.com/2.11.3/manual/jobs.html#scheduled-jobs), except for version 3.0.11 of Rundeck. 

**Source page**
https://docs.rundeck.com/3.0.11/manual/running-jobs.html is the closest equivalent I can find. It doesn't disclose how to get to the crontab scheduling screen.

**Comment by fdevans** [comment]
Current version of jobs scheduling documentation is here:
https://docs.rundeck.com/docs/manual/creating-jobs.html#scheduled-jobs

Let us know if you still need some assistance.
