### ISSUE TITLE
Documentation bug in file api/rundeck-api.md

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/docs#263]
**Describe the bug**
 
The project is not exporting anything in the project , it should be put in the api call example
This is Good 
 curl -X GET -H "X-Rundeck-Auth-Token: aoRGBPd63sJcz9wl4sG1oC8Zme9VT54r" http://rundeckhost:4440/api/19/project/<project>/export/async?exportAll=true

This is not Good
 curl -X GET -H "X-Rundeck-Auth-Token: aoRGBPd63sJcz9wl4sG1oC8Zme9VT54r" http://rundeckhost:4440/api/19/project/<project>/export/async

**Source page**
For the section > https://docs.rundeck.com/docs/api/#project-archive-export-async

**Comment by yogeshkumark** [comment]
i am not sure my API is also not working.

**Comment by fdevans** [comment]
This issue appears to have been fixed.
