### ISSUE TITLE
Documentation bug in file administration/projects/node-execution/powershell.md

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/docs#264]
**Describe the bug**
Not clear if the following configuration is needed for CredSSP:
```
On the remote nodes
winrm quickconfig
​winrm set winrm/config/service/Auth @{Basic="true"}
winrm set winrm/config/service @{AllowUnencrypted="true"}
winrm set winrm/config/winrs @{MaxMemoryPerShellMB="1024"}
```

**Source page**
https://docs.rundeck.com/docs/administration/projects/node-execution/powershell.html#winrm-setting-to-use-powershell-plugin

**Comment by gschueler** [comment]
do you mean it is optional in that case?

**Comment by G3NSVRV** [comment]
it should be optional as was confirmed with ltoledo

**Comment by fdevans** [comment]
Need clearer follow up on this so we can make the necessary changes to the docs and close this out.  Can someone provide the page that needs updating and guidance on what specifically needs to be changed?

**Comment by g3nsvrv** [comment]
activate basic auth is not required for another auth methods, like credssp.

**Comment by gschueler** [comment]
@ltamaster ⬆️
