### ISSUE TITLE
Documentation bug in file manual/01-introduction.md

### ISSUE THREAD

**Issue by jrw** [rundeck/docs#272]
https://docs.rundeck.com/docs/manual/introduction.html mentions Enterpise (spelling!) a couple of times.  It also refers to "Pro" but then leaves out the "Pro" part.  Looks like someone ran s/Pro//g without thinking about it.  Someone with commit rights should read the "Rundeck Enterprise" section to check that it actually makes sense.

**Comment by gschueler** [comment]
thanks
