### ISSUE TITLE
Documentation bug in file tutorials/java-plugin.md

### ISSUE THREAD

**Issue by JaredCE** [rundeck/docs#277]
**Describe the bug**

When running through the **Bootstrapping the plugin project structure**, I get to the step asking me to: `make tools`

This goes well, until step 6 of the Dockerfile, where I encounter this error:

```
> Configure project :
Failed to open repository, trying to work without it org.eclipse.jgit.errors.RepositoryNotFoundException: repository not found: /root/rd/rundeck-cli-f20b69dc8e43462bf71a78dcb549997c86a51995
Could not resolve current position on uninitialized repository, returning default

FAILURE: Build failed with an exception.

* Where:
Build file '/root/rd/rundeck-cli-f20b69dc8e43462bf71a78dcb549997c86a51995/build.gradle' line: 304

* What went wrong:
A problem occurred evaluating root project 'rundeck-cli-f20b69dc8e43462bf71a78dcb549997c86a51995'.
> Cannot add task 'wrapper' as a task with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
ERROR: Service 'rundeck-cli' failed to build: The command '/bin/sh -c cd /root/rd/     && unzip rd.zip     && cd rundeck-cli-${COMMIT}     && gradle --no-daemon :distZip' returned a non-zero code: 1
make: *** [tools/rd-0.1.0-SNAPSHOT/bin/rd] Error 1
```

**Source page**
https://docs.rundeck.com/docs/tutorials/java-plugin.html#bootstrapping-the-plugin-project-structure

**Comment by larajustine** [comment]
I faced the same error. Did you find a solution to it?

**Comment by catalinafocsa** [comment]
I faced the same error too and didn't find a solution for it yet. Did you manage to fix it or approach it somehow in the meanwhile?

**Comment by fdevans** [comment]
Apologize if we missed this error.  This is our documentation repository.  If you are still having trouble with the build process please open an issue on the rundeck/rundeck repository and we can try to offer assistance there.  Please include OS you are building on and version you are trying to build.
