### ISSUE TITLE
Can´t run jobs with ansible when using rundeck

### ISSUE THREAD

**Issue by Supersempfft** [rundeck/docs#289]
When I use a group to run an Ansible Playbook I only get:
Test is a host group in ansibel.

[WARNING]: Could not match supplied host pattern, ignoring: Test
PLAY [Test] ********************************
skipping: no hosts matched

Only host group all works.

**Comment by gschueler** [comment]
this repo is for rundeck documentation issues, if you have a bug report for rundeck, please create an issue in https://github.com/rundeck/rundeck/issues

Please post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!

You can also get more information and links to other ways to get help here: http://rundeck.org/help.html
