### ISSUE TITLE
Documentation bug in file administration/cluster/loadbalancer/haproxy.md

### ISSUE THREAD

**Issue by emiliohh** [rundeck/docs#290]
**Describe the bug**

The CGI script part could be moved at the end of the document or a separated document.  The basic config required for rundeck is what matters the most.

the web.xml file is not exposed in RD3

**Source page**
https://docs.rundeck.com/docs/administration/cluster/loadbalancer/haproxy.html

**Comment by jrmneves** [comment]
Hi @emiliohh ,
I had the same issue and found your bug #223 (which is a duplicate of this bug).  After trying some possible configurations in haproxy, I submitted a [pull request](https://github.com/rundeck/docs/pull/281) to update the documentation (it references bug #223).  It is waiting for the project developers review.

**Comment by emiliohh** [comment]
fixed
