### ISSUE TITLE
Documentation bug in file administration/maintenance/tuning-rundeck.md

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/docs#295]
**Describe the bug**
The line below doesn't work on RPM **/etc/sysconfig/rundeckd**
```
export RDECK_JVM="$RDECK_JVM -Dcom.sun.management.jmxremote"
```

I've used instead 
```
RDECK_JVM_OPTS="$RDECK_JVM -Dcom.sun.management.jmxremote"
```
Which works perfect.

**Source page**
https://docs.rundeck.com/docs/administration/maintenance/tuning-rundeck.html#jmx-instrumentation

**Comment by G3NSVRV** [comment]
it's on the documentation, is just badly formated.

**Comment by jessemarple** [comment]
Issue moved to [rundeck/docs-vuepress #6](https://github.com/rundeck/docs-vuepress/issues/6) via [**ZenHub**](https://www.zenhub.com/)
