### ISSUE TITLE
Documentation bug in file administration/security/authentication.md

### ISSUE THREAD

**Issue by TimLevatich** [rundeck/docs#296]
**Describe the bug**
A clear and concise description of what the documentation issue is.
The text that reaches the right hand edge of my browser window does not wrap properly to the next line. It is hidden from view, so matter what I do to resize my browser window. This happens with both Chrome and Firefox. What good is documentation if you can't read it?

**Source page**
Please include the link or name for the page of the documentation which has the issue.
https://docs.rundeck.com/docs/administration/security/authenticating-users.html

**Comment by fdevans** [comment]
referenced page is no longer available.  Current page with similar content does not wrap in Chrome.  Let us know if you are still experiencing issues.
