### ISSUE TITLE
Documentation bug in file developer/05-notification-plugins.md

### ISSUE THREAD

**Issue by yogeshkumark** [rundeck/docs#297]
**Describe the bug**
A clear and concise description of what the documentation issue is.
we required notification as the jobs are not started for some minutes or hours. 
This is the drawback i saw it from the Rundeck schedular. 
**Source page**
Please include the link or name for the page of the documentation which has the issue.
Many schedular tool, they highlight the jobs are not been triggered due to dependency or issues 

Please keep this request under the enhancement

**Comment by fdevans** [comment]
Thank you for the enhancement request.  We have noted it.
