### ISSUE TITLE
Documentation bug in file upgrading/upgrading-to-rundeck-3.1.md

### ISSUE THREAD

**Issue by gufertum** [rundeck/docs#298]
**Describe the bug**
Upgrade docs from 3.0 to 3.1 miss to mention, that the encryption changed (from keys file to yasypt (in db?). Therefore, after the update, I had to add all my keys again, because the key storage was empty (not migrated).

Also the SCM plugin did not work anymore, because the config was missing (reset to defaultl?). The config-file was still there, but the credentials had to be re-entered in the GUI.

A hint in the docs should be the minimum, so users can prepare for the breaking changes. For the keys, a migration procedure should be possible, or at least, the key storage should not be empty, because this results in grepping all the needed key/paths.
For the SCM the migration should work automatically (I could not find any changes).

**Source page**
https://docs.rundeck.com/3.1.0/upgrading/upgrade-to-rundeck-3.1.html

**Comment by mveroone** [comment]
I think i'm facing the same issue regarding SCM. All my SCM configurations seem to disappear when upgrading.

**Comment by fdevans** [comment]
@gufertum Not sure if this got lost in our Docs repository or not.  Are you still having the same issue with your upgrade procedure?

**Comment by gufertum** [comment]
@fdevans I'm currently not upgrading again... so I cannot tell you if it is still a problem. Wanted just to report it. To not have to roll back I re-imported all my keys and got it going, but i did not have too many of them, otherwise this would not be an option...

FYI: We are currently on version 3.2.1, the last update from 3.1 to 3.2 was OK.

**Comment by mveroone** [comment]
As for us, we've upgraded all our machins to 3.2.1 too.
I think the issue was we came from 2.9.11 and we had to add `rundeck.projectsStorageType=filesystem` but I'm not sure. What I'm sure is that we found a solution to our issue and were able to upgrade without SCM config loss

**Comment by fdevans** [comment]
Thank you for the feedback.  I'll check in with the support team to see if there is anything we can include for others making the same upgrade jump.  Glad the more recent upgrades have been going better.
