### ISSUE TITLE
OSS repo path and steps

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/docs#30]
http://rundeck.org/3.0.x-SNAPSHOT/administration/install/ubuntudebian.html
OSS install section should point to "deb https://rundeck.bintray.com/rundeck-deb /", second line is not needed, third and fourth lines do the same action:

echo "deb https://rundeck.bintray.com/rundeck-deb /" | sudo tee -a /etc/apt/sources.list.d/rundeck.list
USE THIS OR THE ONE BELOW curl 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray' | sudo apt-key add -
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61
sudo apt-get update
sudo apt-get install rundeck

**Comment by gschueler** [comment]
@jplassnibatt can you send a PR with those changes?

**Comment by jplassnibatt** [comment]
PR done.

**Comment by jplassnibatt** [comment]
fixed by #32
