### ISSUE TITLE
Bind to localhost documentation

### ISSUE THREAD

**Issue by wpbullet** [rundeck/docs#305]
When googling I found https://rundeck.lighthouseapp.com/projects/59277/tickets/466-add-ability-to-bind-4440-to-localhost-address and https://github.com/rundeck/rundeck/commit/1067a6697b1085be612e12c0a54ece85d1060d83

However I adding this `http.server.host=127.0.0.1` in either `/etc/rundeck/profile` or `/etc/rundeck/rundeck-config.properties` is not working.

**Comment by fdevans** [comment]
I believe this is resolved with the current Rundeck versions.  If you are still having issues on a current version please let us know.

**Comment by marcinhlybin** [comment]
To bind to localhost set:

```
server.address=127.0.0.1
```

in `/etc/rundeck/rundeck-config.properties` file and restart `rundeckd` service.
It works in Rundeck 3.3.5.
