### ISSUE TITLE
Job option automatic datestamp ${DATE:..} is not documented

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#309]
Issue type: Documentation

You can use the string `${DATE:format}` as a job option vlaue, which will be converted when the job/command is executed.

`${DATE:format}` current date in format used by the Java [SimpleDateFormatter][1]

`${DATE+2:format}` two days from now

`${DATE-2:format}` two days ago

  [1]: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by RAJMODI038** [comment]
Can I add or minus "minutes, seconds" using this? It's like, supports days only.

**Comment by fablemarchand** [comment]
> Can I add or minus "minutes, seconds" using this? It's like, supports days only.

have you find a solution to play on minutes or second ?

**Comment by gaddman** [comment]
It only supports days - see the code for `expandDateStrings` in [ExecutionService.groovy](https://github.com/rundeck/rundeck/blob/33e876161c9d4b546b9511ca14ca616c608ea80b/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L2006-L2043).
