### ISSUE TITLE
JOB-XML documentation mistake

### ISSUE THREAD

**Issue by ghost** [rundeck/docs#310]
Issue type: Bug report

Bug in documentaion (see attached image)
http://rundeck.org/docs/man5/job-xml.html

Schedule \ weekday \ day example

> 1-5 days "sun-sat"

must be replaced with

`1-5 days "sun-thu"`

![screen shot 2017-05-25 at 13 03 33](https://cloud.githubusercontent.com/assets/1070039/26441692/f6c0ccde-414a-11e7-9485-de40b9dd15ee.png)

**Comment by fdevans** [comment]
I'm confused why this must be replaced with "sun-thu" is there something technically wrong with "sun-sat"?

For reference, this is the current location:
https://docs.rundeck.com/docs/manual/document-format-reference/job-v20.html#weekday

**Comment by fdevans** [comment]
I see where the confusion is.  I've updated to `1-7` which are the values Quartz uses for day of week per docs here: http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html
