### ISSUE TITLE
Documentation has conflicting information on acceptable values for projectsStorageType

### ISSUE THREAD

**Issue by csgyuricza** [rundeck/docs#312]
Issue type: Bug report (documentation)

The Rundeck Storage Facility page lists 2 possible values: `db` or `file`:
http://rundeck.org/docs/administration/storage-facility.html#storage-backends

However the Project Setup page lists `db` or `filesystem`:
http://rundeck.org/docs/administration/project-setup.html

Which one is correct?

**My Rundeck detail**

* Rundeck version: 2.10.8

**Comment by fdevans** [comment]
Appears to be completed and fixed in Docs
