### ISSUE TITLE
Access the encrypted storage keys in NodeExecutor plugin

### ISSUE THREAD

**Issue by jcdsilva** [rundeck/docs#313]
Issue type: Seek Information

I have encrypted the storage keys using jasypt

_rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.config.encryptorType=custom
rundeck.storage.converter.1.config.passwordSysPropName=encwithaessha256128
rundeck.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.storage.converter.1.config.provider=BC_

I have a customized python script which is used as NodeExecutor (SSH plugin).

Questions

**1) How can I access these keys in SSH plugin?**

Is it like below:

Node level: ssh-key-storage-path attribute on the Node. Applies only to the target node.
Project level: project.ssh-key-storage-path property in project.properties. Applies to any project node by default.
Rundeck level: framework.ssh-key-storage-path property in framework.properties. Applies to all projects by default.

**2) How can I decrypt these keys and use in SSH plugin** 

My Rundeck detail

Rundeck version: 2.8.1_1
install type: (rpm,deb,war,launcher?) rpm
OS Name/version: Linux
DB Type/version: mysql? postgres? h2?..

**Comment by fdevans** [comment]
@jcdsilva I'm not sure why this ended up in our Docs repository.  Looks like that's not where it started.  Is this still an open question for you on a more recent Rundeck version?

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce on the rundeck/rundeck repository.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
