### ISSUE TITLE
Enterprise Quickstart docs are out of date

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#325]
**Describe the bug**

Quickstart instructions no longer work

**Source page**

https://github.com/rundeck/docs/edit/3.1.x/docs/enterprise/quickstart.md

**Comment by fdevans** [comment]
Will test using latest code and instructions.  Also need to update the https://docs.rundeck.com/docs/enterprise/quickstart.html#what-is-rundeck-enterprise section after the new "What is Enterprise" landing page is done.

**Comment by fdevans** [comment]
Based on feedback internally we will redirect this page to the new "What is Enterprise" page when it's ready next week.

**Comment by fdevans** [comment]
Depends on #487
