### ISSUE TITLE
running a job wrong

### ISSUE THREAD

**Issue by zhangdavids** [rundeck/docs#332]
**Describe the bug**
A clear and concise description of what the documentation issue is.

running a job describe here:

when use python 

{
    "argString":"...",
    "loglevel":"...",
    "asUser":"...",
    "filter":"...",
    "runAtTime":"...",
    "options": {
        "myopt1":"value",
        ...
    }
}

have like this one 

{
"options":
{"version": "123"
}
}

passing these but got Option \'version\' is required

seem strange

**Source page**
Please include the link or name for the page of the documentation which has the issue.

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
