### ISSUE TITLE
Realm.properties: users should be aware to avoid CRYPT: only first 8 chars are used

### ISSUE THREAD

**Issue by booshlinux** [rundeck/docs#334]
**Describe the bug**
The bug is apparent when a user is placed in `realm.properties` with the `CRYPT` encryption scheme in use, along with ACL lists. The length of the password encrypted does not matter. If a password was 15 characters long, and the first 8 characters of that password are correct, authentication succeeds.

**My Rundeck detail**

* Rundeck version: 3.0.23
* install type: deb
* OS Name/version: Ubuntu 18.04

**To Reproduce**
1. Create a new user, using `CRYPT` and making the password longer than 8 characters.
(This password was set to `passwordthatislongerthan18`)
`test_user: CRYPT:teobtLiiDGEOk,admin`
2. Make a curl request with the correct password:
```
$ curl -X POST -I 'https://xyz:4443/j_security_check?j_username=test_user&j_password=passwordthatislongerthan18'
HTTP/1.1 302 Found
Date: Fri, 25 Oct 2019 20:59:43 GMT
Set-Cookie: JSESSIONID=node0g9dvnfgcdc9h1hhqxopce0ffd7220.node0;Path=/;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: https://xyz:4443/            <--- Success, 302 does not point to /user/error or /user/login
Content-Length: 0
```
3. Make another curl request, but only retain the first 8 characters of the password:
```
$ curl -X POST -I 'https://xyz:4443/j_security_check?j_username=test_user&j_password=password'
HTTP/1.1 302 Found
Date: Fri, 25 Oct 2019 21:02:07 GMT
Set-Cookie: JSESSIONID=node0ddsobwpa7bdtzodrfr0i9gf67230.node0;Path=/;Secure;HttpOnly
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Location: https://xyz:4443/     <--- Success, 302 does not point to /user/error or /user/login
Content-Length: 0
```

**Expected behavior**
This should be pretty straightforward.

**Additional context**
If this is a limitation to CRYPT, more prominent documentation should be required about this limitation.

**Comment by fdevans** [comment]
this was done at some point.  There is a note on the page now.
