### ISSUE TITLE
Commands containing an option reference and an extra '@' not parsed correctly

### ISSUE THREAD

**Issue by binaryfire** [rundeck/docs#335]
**Describe the bug**
Hi guys. Rundeck is not parsing commands correctly when an extra '@' is present in a line that uses an option reference

**My Rundeck detail**

* Rundeck version: latest
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**

1. Use the following in a script:
**git clone git@gitlab.com:helloword/@option.test_group@/my-repo.git**

2. Run script

3. See error:
**fatal: repository 'gitoption.test_group@/my-repo.git' does not exist**

I'm working around this atm by first setting **TEST_GROUP="@option.test_group@"** and then running **git clone git@gitlab.com:helloword/$TEST_GROUP/my-repo.git**

Cheers

**Comment by carlosrfranco** [comment]
Transferring this issue to docs repo

**Comment by carlosrfranco** [comment]
It is already documented in: https://docs.rundeck.com/docs/manual/job-options.html#script-usage
`Escaping Replacement Token`
