### ISSUE TITLE
Installation references rundeckpro-cluster package

### ISSUE THREAD

**Issue by dutchrapley** [rundeck/docs#350]
Installation documentation needs to be updated to reference rundeckpro-enterprise.

https://docs.rundeck.com/docs/administration/install/linux-rpm.html#open-source-rundeck

**Comment by fdevans** [comment]
There is now a https://docs.rundeck.com/docs/administration/install/linux-rpm.html#rundeck-enterprise section on this page.  Is that solving what the original request was meant to highlight?
