### ISSUE TITLE
GUI customization document:  incorrect description for Startpage default value.

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/docs#37]
http://rundeck.org/2.4.1/administration/gui-customization.html

Mentions:

> `rundeck.gui.startpage` >>>>    Change the default page shown after choosing a project. values: 'run', 'jobs' or 'history'. Default: 'jobs'.

The default is NOT `jobs` page but the `Project Overview` (home) page

![image](https://user-images.githubusercontent.com/31705339/43229671-9ebcf0f6-9033-11e8-8c8a-313cd67ac04d.png)

**Comment by gschueler** [comment]
the linked docs refer to version 2.4.2 core, not pro.  pro 2.4.2 is core 2.11.5, these docs appear correct: http://rundeck.org/2.11.5/administration/gui-customization.html

closing this issue
