### ISSUE TITLE
Update List of Node Executors

### ISSUE THREAD

**Issue by dutchrapley** [rundeck/docs#397]
**Describe the bug**
Update the list of node executors that can be set in a node definition with `node-executor=`.

**Source page**
https://docs.rundeck.com/docs/administration/projects/node-execution/builtin.html#built-in-node-execution-plugins-2

**Comment by gschueler** [comment]
hmm, i think that page is confusing.  it mixes in some general information about node executors/file copiers, then the list of built-in implementations. this page has a longer list including the bundled plugins https://docs.rundeck.com/docs/plugins/

**Comment by fdevans** [comment]
What if we just directed them to the /docs/plugins page to see the current list of Node Executors instead of maintaining two lists?

**Comment by gschueler** [comment]
that sounds fine
