### ISSUE TITLE
Option with ${Date} Shows 1 Year ahead

### ISSUE THREAD

**Issue by kjtsm** [rundeck/docs#399]
**Describe the bug**
Rundeck Version: 3.0.24-20190719
Option Type: Text
Input Type: Plain text
Default Value: ${DATE:MM-dd-YYYY}

The option value should be 12/29/2019 when you run today(on 12/29/2019) but it has 12/29/2020.

It worked yesterday on 12/28/2019, the option variable had 12/28/2018.
No server changes made.
The server date is synced with NTP and shows 12/29/2019 today.

**Source page**
Looks like someone else is reporting a similar bug.
https://github.com/rundeck/docs/issues/309#issuecomment-356966547

**Comment by jiomanRO** [comment]
Hello,
Same issue with using job option ${DATE:YYYY-MM-dd HHmm}: - starting with 29.12.2019 00:00 it returns wrongly one year in the future: year 2020 - reproduced on an older Rundeck 2.7.3-1 and also on a newer Rundeck 3.0.12.
So also today 30.12.2019, the value returned for year is 2020.

**Comment by bloblek** [comment]
Hi,
@jiomanRO Please change ${DATE:YYYY-MM-dd HHmm} to ${DATE:yyyy-MM-dd HHmm}. 
More info: http://dangoldin.com/2019/01/06/javas-simpledateformat-yyyy-vs-yyyy/
That should help.

**Comment by jiomanRO** [comment]
Hello,
@bloblek Thanks for the solution. Indeed changing the format to lower-case fixed the issue. The documentation from Rundeck points to [https://momentjs.com/docs/#/displaying/format/](url) but doesn't contain this very useful info.
Thanks again.

**Comment by gschueler** [comment]
note, this page https://docs.rundeck.com/docs/manual/job-options.html#defining-an-option details the use of `${DATE:format}`, and also links to java [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) with the correct formatting information.   `yyyy` is the correct format for the year, not `YYYY` (week year)
