### ISSUE TITLE
Documentation Bug - Plugin UI behaviour

### ISSUE THREAD

**Issue by g3nsvrv** [rundeck/docs#400]
**Describe the bug**
The information presented on the developer documentation on Pluging UI behaviour is outdated.

**Source page**
https://docs.rundeck.com/docs/developer/11-ui-plugins.html#behavior

**Comment by gschueler** [comment]
can you be more specific about what is outdated?

**Comment by fdevans** [comment]
@G3NSVRV  can you please provide details or content that needs to be updated?

**Comment by g3nsvrv** [comment]
far as I was told by @ltamaster, the UI plugins applies to all pages.

**Comment by gschueler** [comment]
that is correct, UI plugins load on all pages by default now
