### ISSUE TITLE
After 3.0 upgrade, threadCount setting in rundeck-configuration.properties ignored

### ISSUE THREAD

**Issue by brendlerjg** [rundeck/docs#44]
After upgrade

in /etc/rundeck-configuation.properties:
`org.quartz.threadPool.threadCount = 50`

System Report page constantly displays:
"Quartz Scheduler thread usage is currently at 100%: 10/10 Threads in use.
Job and Ad-hoc executions will be queued until previous executions complete."

APIVERSION : 25
BASE : /var/lib/rundeck
BUILD : 3.0.0-20180727
BUILDGIT : v3.0.0-0-gb18732d
NODE : localhost
SERVERUUID :
VERSION : 3.0.0-20180727

76 Active Threads at the moment.  The backlog is too high now.  We are making some changes to job architecture to reduce this demand (fewer jobs waiting for input), but we'd like to have control.

Multiple reboots, no change.

This is on Fedora 27 with everything up to date.

Short of a fresh build on a clean platform, what should I try?

**Comment by brendlerjg** [comment]
That fixed it.

Also, I mistakenly referenced the "org.quartz" line above, which I was trying at the time.  We were previously using the setting that's in the documentation (and it wasn't working since the upgrade to 3.0):
`quartz.props.threadPool.threadCount = 50`

For clarity, the line that worked is what you suggested:
`quartz.threadPool.threadCount = 50`

**Comment by puremourning** [comment]
Changing the docs is fine, but this is mandatory configuration change on upgrade. Was this in the upgrade guide for 3.0?

I don't see it here; https://docs.rundeck.com/docs/upgrading/upgrade-to-rundeck-3.x.html
or here: https://docs.rundeck.com/docs/upgrading/upgrade-to-rundeck-3.1.html
