### ISSUE TITLE
Java Version(s)

### ISSUE THREAD

**Issue by edwrd-t-justice** [rundeck/docs#446]
What version(s) of java work with rundeck? I see 1.8 listed and recommended but that is quite old. Does it work with 11? Will it work with 11 or anything newer in the future? I don't want to commit to buying an enterprise product that isn't being updated to use current components.

Thanks!

From the documentation page:

The install process requires that the latest version of Java 8 be installed. Both the Open JDK and Sun/Oracle JVMs can be used. You must have the JAVA_HOME environment variable defined in your environment before running the launcher. The RPM will use the java found on your path. See Setting JAVA_HOME if you want to run a different version of java.

Verify your Java version to check it meets the requirement:

**Comment by fdevans** [comment]
Version 11 support is due out later this year.

**Comment by edwrd-t-justice** [comment]
Thank you for the update.
