### ISSUE TITLE
Undocumented - Require role for login 

### ISSUE THREAD

**Issue by pwonson** [rundeck/docs#451]
**Describe the bug**
see google doc
https://docs.google.com/document/d/1kbJglQJ0tpBkR6Ap-tiGn986bGFsHR5fgC6j14omQ_g/edit?usp=sharing

By default if a user passes authentication -- that is they supply a valid username and password, they are allowed to login to Rundeck but cannot access any projects. 

This is an example of the page the user sees after authenticating:
<image>

You can prevent users from logging in by adding the following JVM system parameter:

-Drundeck.security.requiredRole=Your_Role_Name

Now only users that are in the group Your_Role_Name can log into Rundeck. (Note that if a user is a member of the required role but no ACL policies match any of their role names they will see the page above.)

When a user that does not have the required role tries to login with valid credentials they see the following message:

<image>

**Source page**
Should be added to the following page:

https://docs.rundeck.com/docs/administration/security/authentication.html

**Comment by fdevans** [comment]
Do you have a suggestion where on that page this would fit well?  There is a LOT going on on that page already.

**Comment by pam-rundeck** [comment]
The best place to put it would be in the configuration section

https://docs.rundeck.com/docs/administration/security/authentication.html#configuration

However I think this page and the corresponding pages for Okta, Ping, and OAuth should be rewritten and restructured.
