### ISSUE TITLE
"The user has to explicitly select target nodes"

### ISSUE THREAD

**Issue by VivianeHonda** [rundeck/docs#469]
When the option in Node Selection is: "The user has to explicitly select target nodes". 

If the user does not specify the node, the complete inventory is being sent. Even if you have put a filter in the JOB it is not being respected and all the servers in the inventory are running
[Rundeckbug.docx](https://github.com/rundeck/docs/files/4402995/Rundeckbug.docx)

**Source page**
Please include the link or name for the page of the documentation which has the issue.

**Comment by jessemarple** [comment]
This repo and its issues are specific to the Rundeck Docs.

Please visit https://github.com/rundeck/rundeck/issues to add an issue.

Please note we do not open .doc/x attachments.
