### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by sirvig** [rundeck/docs#50]
The security role section of the 3.0 documentation (Rundeck Documentation (3.0.0) | Administrator Guide | Security  | Authenticating Users) still references "RPM/debian install path: /var/lib/rundeck/exp/webapp/WEB-INF/web.xml".  However, after a fresh RPM install on RHEL7, the /var/lib/rundeck/exp/webapp is blank.  Where do we set the default security role (especially for changing to LDAP authentication)?

**Comment by gschueler** [comment]
@sirvig we are working on fixing that doc right now: https://github.com/rundeck/docs/pull/48

there is no need for a default security role anymore
