### ISSUE TITLE
Missing Content: Built-In Workflow Steps

### ISSUE THREAD

**Issue by g3nsvrv** [rundeck/docs#503]
**Describe the bug**
No content on the link, it appears on the results on the built in search

**Source page**
https://docs.rundeck.com/docs/manual/workflow-steps/builtin.html#global-variable

**Comment by fdevans** [comment]
Thanks @G3NSVRV I've added it to our upcoming Bounty listing project.

**Comment by fdevans** [comment]
@chrismcg14 added the remaining built-in workflow steps in PR #603
