### ISSUE TITLE
Broken links: links referenced in 2.11 docs that have moved should be forwarded to new locations if possible

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#58]
example:

old: http://rundeck.org/docs/administration/configuration-file-reference.html#framework.properties
new: http://rundeck.org/docs/administration/configuration/configuration-file-reference.html#framework.properties

ref: https://github.com/rundeck/rundeck/issues/3788

**Comment by fdevans** [comment]
Neither page exists anymore.  Do we have anywhere we can track 403 errors with referrer page for docs site?
