### ISSUE TITLE
Broken link on downloads page

### ISSUE THREAD

**Issue by Kribylet** [rundeck/docs#580]
A link to the Getting Started guide, situated under the header "Next Steps", is broken on the downloads page.

Problem page: https://docs.rundeck.com/downloads.html

Correct link: https://docs.rundeck.com/docs/manual/03-getting-started.html

The broken link points to: https://docs.rundeck.com/docs/manual/getting-started.html

**Comment by fdevans** [comment]
@mishingo Did we fix this on the Downloads page?

**Comment by mishingo** [comment]
PR created: https://github.com/rundeck/rundeck-org-site/pull/4
