### ISSUE TITLE
Inconsistent link behaviour on Nodes page

### ISSUE THREAD

**Issue by Kribylet** [rundeck/docs#581]
There is a link that causes issues in Mozilla Firefox 72.0.2 in the User Guide Nodes section, under the Overview header.

I'm not sure this is an issue on all browsers.

Issue page: https://docs.rundeck.com/docs/manual/05-nodes.html#overview

Issue link: https://docs.rundeck.com/docs/manual/09-configure.html#resource-model-sources-configuration

The link is broken when followed from the Nodes page, but works when copied and pasted into the browser.

Issue steps:
1. Go to https://docs.rundeck.com/docs/manual/05-nodes.html#overview
2. Click the link from the Nodes page (issue page)
3. Broken link to 404.

Working steps:
1. Copy the issue link 
2. Paste and go from anywhere, including the issue page
3. Works as expected

**Comment by fdevans** [comment]
Thanks @Kribylet for finding that.  I've pushed some updates.  They will be public in the next day or so.
