### ISSUE TITLE
Documentation on Scheduling Jobs for Future Execution via API are unclear

### ISSUE THREAD

**Issue by wreill327** [rundeck/docs#590]
When attempting to schedule a job with required options via the API (using python requests module) the JSON is not being properly read and thus the option requirements are not being fulfilled. Below is a skeleton version of the code being used;

```
# !/usr/bin/python3

import requests

url = "https://rundeck.some.url/api/1/job/some-job-id/run"
api_key = get_auth()

headers = {
'X-Rundeck-Auth-Token': api_key,
'Content-Type': 'application/json'
}

payload = {
"runAtTime": "2020-08-03T23:00:00-0400",
"options": {
"opt1": "option1data",
"opt2": "option2data",
"opt3": "option3data"
}}

response = requests.request("POST", url, data=payload, headers=headers)
print(response)
print(response.text)
```

Running the above in any variation always yields the below error;
```
<Response [400]>
<result error='true' apiversion='35'>
  <error code='api.error.job.options-invalid'>
    <message>Job options were not valid: Option 'opt1' is required.
Option 'opt2' is required.
Option 'opt3' is required.</message>
  </error>
</result>
```

Note that the 3 required options configured on the job are: opt1, opt2, opt3. opt1 is a text field where opt2 and opt3 are strictly enforced from a list of allowable options.

Per documentation noted at https://docs.rundeck.com/docs/api/rundeck-api.html#listing-jobs, all parameters associated to this API endpoint are optional, and the "Options" portion appears to be properly formatted. Additionally, the "API Explorer" located at https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k?version=latest#36bbd9c4-3186-56f4-aae2-90f5c9f097a8 offers no additional insight into proper formatting fo this payload.  

Is there something I am missing within the documentation, or is this an issue within Rundeck for evaluating incoming payloads including "option" parameters?

**Comment by chrismcg14** [comment]
Hi wreill237, in order to pass JSON data via the API, the API Version needs to be 14 or higher. If you use 
"url = https://rundeck.some.url/api/14/job/some-job-id/run", that should work! Good luck!

**Comment by chrismcg14** [comment]
Hi wreill237, in order to pass JSON data via the API, the API Version needs to be 14 or higher. If you use
"url = https://rundeck.some.url/api/14/job/some-job-id/run", that should work! Good luck!
