### ISSUE TITLE
Missing documentation: Data Capture guide

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#61]
Need "Guides/howto" section:

Need "Capturing data for use in later workflow steps" guide, showing Data Capture plugin and usage.

**Comment by gschueler** [comment]
one piece of content for guide: how to pass variables from a job reference to a parent job

ref: https://github.com/rundeck/rundeck/issues/3062#issuecomment-413184066

**Comment by jospradlin** [comment]
I'd actually suggest a serious 'Workflow Integration' guide.   The difficulty of understanding workflow logic and variable passing is somewhat painful (compared to other workflow products).   I'd love to see something like an 'Import Options' and 'Export Options' for each Job so you can streamline the data throughout the workflow.

**Comment by juresaht2** [comment]
Please add clarification regarding the `${data.variable@mynode}` syntax as per: https://github.com/rundeck/rundeck/issues/2973

At present the documentation only tells you to use $data.variable in the subsequent steps and fails to mention that:

1. $data variables cannot actually be used in subsequent steps, but needs to be passed to an option
2. when referencing the $data variables in a workflow step, the `@mynode` syntax has to be used to determine which node the variable comes from
