### ISSUE TITLE
White list of sites

### ISSUE THREAD

**Issue by pwonson** [rundeck/docs#612]
**Describe the bug**
Need a list of sites (URL) to white list, for example for the rundeck plugin manager.
**Source page**
https://docs.rundeck.com/docs/administration/install/system-requirements.html#system-requirements

**Comment by fdevans** [comment]
@ProTip Can you compile this list and I'll take over for the content part?

**Comment by ProTip** [comment]
@fdevans https://api.rundeck.com supplies the information for news, releases, and the plugin content.
