### ISSUE TITLE
Add a new page for the WebHooks log event plugin. 

### ISSUE THREAD

**Issue by chrismcg14** [rundeck/docs#615]
There are pages for the other three plugins under WebHooks handlers (run job, advanced run job and PagerDuty). Need to add a page for WebHook log event plugin. I would assume a new page under handlers like the three other pages for the other WebHook plugins. To be confirmed by @fdevans. 

These are the pages that we already have for the other WebHooks plugins:

https://docs.rundeck.com/docs/manual/webhooks/run-job.html#usage
https://docs.rundeck.com/docs/manual/webhooks/advanced-run-job.html#general-settings
https://docs.rundeck.com/docs/manual/webhooks/pagerduty-run-job.html

**Comment by fdevans** [comment]
Yes, we can add it as it's own page.  Let's describe the use-case for the plugin and provide details where/how to find the webhook log file, what types of information it will contain, etc.
