### ISSUE TITLE
RPM Installation change location instructions missing

### ISSUE THREAD

**Issue by pwonson** [rundeck/docs#621]
**Describe the bug**
For RPM installations use the following syntax to change the installation paths:

rpm -ivh --relocate /etc/rundeck=/apps/rundeck/etc --relocate /var/lib/rundeck=/apps/rundeck --relocate /usr/bin=/apps/rundeck/bin rundeckpro-enterprise-3.3.2.20200817-1.noarch.rpm

**Source page**
https://docs.rundeck.com/docs/administration/install/linux-rpm.html#rundeck-enterprise

**Comment by fdevans** [comment]
This is just part of the RPM command and not something we should "encourage" customers to do by documenting it.
