### ISSUE TITLE
Missing Notification Documentation

### ISSUE THREAD

**Issue by chrismcg14** [rundeck/docs#640]
I can only find docs for jira, service now, webhook and email. Need docs for splunkevent, pager duty, slack, etc.

**Comment by FixFlare** [comment]
@fdevans I don't think this should have been closed since we are still missing splunk event documentation.

That's exactly how I found this page on google.

**Comment by fdevans** [comment]
You're right.  Since we revamped most of the others on the list I'll open a new issue for Splunk.  I believe the latest docs for that are here but we should have something in our docs on it.  https://splunkbase.splunk.com/app/4120/#/details

**Comment by fdevans** [comment]
Note: It was closed since it was referenced in the merged PR

**Comment by FixFlare** [comment]
@fdevans  correct me if I'm wrong but I think we're talking about two different things.

There is an app that is installed on the splunk side for Rundeck integration (what you're talking about)

and then there is a "Splunk Event" under the Notification options for a Job (what I am talking about)

As a new enterprise customer I'm trying to use it for the first time, it fails, I have no idea where to look for why it is failing or how to proceed.

I found:

[2020-11-18T14:22:26,615] ERROR services.NotificationService [quartzScheduler_Worker-2] - Notification Failed: splunk-raw-collector

in the rundeck log but it doesn't lead me in any direction, to be fair, a useless error message. Definitely need documentation on Splunk Event Notification (raw and json).

**Comment by fdevans** [comment]
I was just offering what we have today on the Splunk page.  I've already opened #699 to address docs on our site for the Notification.
