### ISSUE TITLE
RPM/Yum upgrade fails to mention the rundeck-config rpm

### ISSUE THREAD

**Issue by gschueler** [rundeck/docs#67]
ref this rundeck issue: https://github.com/rundeck/rundeck/issues/3817#issuecomment-412341892

without updating rundeck-config, the /etc/rundeck/profile was not correct

**Comment by ltamaster** [comment]
Hey @gschueler ,

I double check the upgrade docs and it is mentioned here. Not sure if this is enough.

<img width="1124" alt="screenshot 2018-08-14 10 30 15" src="https://user-images.githubusercontent.com/6034968/44094659-27c70fac-9fad-11e8-9e8b-7e5395093164.png">

**Comment by gschueler** [comment]
instructions on rundeck.org/downloads.html did not specify upgrading using `yum upgrade rundeck rundeck-config`.  I have updated that https://github.com/rundeck/rundeck-org-site/commit/2b2becd3116a3c317f0e03df85d702081a17ace3
