### ISSUE TITLE
Document sidebar project list and user cache feature settings

### ISSUE THREAD

**Issue by ProTip** [rundeck/docs#682]
Introduced in rundeck/rundeck#6523
```
rundeck.feature.sidebarProjectListing.enabled=false
rundeck.feature.userSessionProjectsCache.enabled=false
```

**Comment by fdevans** [comment]
The settings above are not the defaults right?  Is there a valid end-user situation where they would want to disable the userSessionProjectsCache or should that remain a backend driven setting change?

**Comment by ProTip** [comment]
@fdevans `true` is the default for both. The ability to disable the user session project cache is, I believe, largely a mitigation for unforeseen issues.

**Comment by fdevans** [comment]
i think this is no longer valid or an issue
