### ISSUE TITLE
Plugins User Guide for 3.X.X

### ISSUE THREAD

**Issue by timhughes** [rundeck/docs#76]
There are no docs for using plugins with the 3 series. 

https://rundeck.org/docs/ 

There are docs for 2 series https://rundeck.org/2.11.5/plugins-user-guide/index.html

**Comment by gschueler** [comment]
We are in the process of revamping the plugins sections in the docs. In 3.0.5 docs we added this page https://rundeck.org/docs/plugins/index.html And now within specific sections of the user manual or administration guide (as relevant) we link to the appropriate plugins.

Aside from that, was there anything else about the current docs with respect to plugins that you could not find?

**Comment by timhughes** [comment]
No that is fine, we are going with the 2.x series for the time being
