### ISSUE TITLE
Does this section from the MySQL setup page still apply?

### ISSUE THREAD

**Issue by binaryfire** [rundeck/docs#779]
Hi guys,

The MySQL setup section (https://docs.rundeck.com/docs/administration/configuration/database/mysql.html#configure-mysql) includes the following instructions:

**After first Rundeck start run the following SQL queries:

use <rundeck_database>;
ALTER TABLE `event_subscription` ROW_FORMAT=dynamic;
ALTER TABLE `reaction` ROW_FORMAT=dynamic;
ALTER TABLE `reaction_event` ROW_FORMAT=dynamic;**

I've just installed v3.3.10 and those tables aren't present in the database. Is this outdated info?

**Comment by gschueler** [comment]
@binaryfire what version of Mysql are you using?

**Comment by binaryfire** [comment]
@gschueler Hey Greg. I'm using MariaDB 10.5

**Comment by fdevans** [comment]
@binaryfire These are irrelevant to that setup.
