### ISSUE TITLE
Email Groovy and Properties config are wrong

### ISSUE THREAD

**Issue by jgarces-pd** [rundeck/docs#856]
## **Describe the bug**
Email Groovy and Properties config are wrong. On RPM and WAR installations you can use both without "translating the rundeck-config.properties into a groovy format", and is being detected by Rundeck automatically without making any extra configuration, like mentioned here that it says is required (not required at all):

https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#specify-config-file-location

Also this is wrong:

```
Specify config file location
You will need to point rundeck at the new filename when you start up rundeck:

Launcher:

  java -jar -Drundeck.config.name=rundeck-config.groovy rundeck-launcher.jar
Copied!
RPM: Add this to the /etc/sysconfig/rundeckd file:

    export RDECK_CONFIG_FILE="/etc/rundeck/rundeck-config.groovy"
Copied!
RPM/DEB: Add this to the /etc/default/rundeckd file:

    export RDECK_CONFIG_FILE="/etc/rundeck/rundeck-config.groovy"
```

Based on this you can configure both files.

```
Advanced SMTP settings
If you need more advanced configuration (e.g., authenticated and secured over SSL), see the grails Mail plugin configuration: Grails Mail Configuration(opens new window)

The caveat for using this is that in our experience it requires using a .groovy formatted configuration file to support the extended configuration properties.

See Groovy config format.
```

From: https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#groovy-config-format
```
Groovy config format
If you would prefer to use Groovy for the config file, you can use rundeck-config.groovy instead of rundeck-config.properties. Or, you can use a combination of the two (i.e. some settings configured in the properties file and some in the Groovy file).
```

This was tested on 3.3.11 RPM and 3.3.8 WAR windows and works perfect.

## **Source page**
https://docs.rundeck.com/docs/administration/configuration/email-settings.html#advanced-smtp-settings

**Comment by jgarces-pd** [comment]
## Also, It can be simply configured in this way:

### etc/profile.bat
```shell
set RDECK_CLI_OPTS=-Xmx2G -Dfile.encoding=UTF-8 -Drd.encryption.default.password=rundeck
```
### rundeck-config.properties
```properties
#### Email ####
grails.mail.host=smtp.gmail.com
grails.mail.port=587
grails.mail.username=jgarces@rundeck.com
grails.mail.password=ENC(kjh2k3jh5k2h35)
```
### rundeck-config.groovy
```groovy
grails {
   mail {
     props = ["mail.smtp.starttls.enable":"true",
              "mail.smtp.port":"587"]
   }
}
```

**Comment by fdevans** [comment]
I'm not clear what the recommendation is to fix this?  If you submit a PR with the proposed doc changes we can review them.
