### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Abbruzz** [rundeck/docs#872]
There are two dead links in the Rundeck documentation 1) see link to the User Guide and the 2) Installation Instructions here on the page https://docs.rundeck.com/docs/

**Comment by Abbruzz** [comment]
Not sure if this is still work in progress. The broken link issue still exists for the Installation Instructions. Something is wonky with the User Guide link too - takes you to an intermediary page "This page has moved here."

**Comment by fdevans** [comment]
Make sure you do a hard refresh of the page or click the refresh content button.
