### ISSUE TITLE
Docker : grails.plugin.databasemigration.updateOnStart environment variable missing

### ISSUE THREAD

**Issue by MurphySunset** [rundeck/docs#873]
Hi there,

**Describe the bug**
In the docker part of the docs, there *might* be an environment variable missing, the one which sets `grails.plugin.databasemigration.updateOnStart` to `true`, so that we can update the container (a typical pull-down-up is not sufficient here).

**Source page**
https://docs.rundeck.com/docs/administration/configuration/docker.html#environment-variables

Thanks!

**Comment by fdevans** [comment]
Thanks for catching that this was missing.
