### ISSUE TITLE
Needs clarification about what is considered misfire

### ISSUE THREAD

**Issue by jgarces-pd** [rundeck/docs#879]
## Description
Needs clarification about what is considered misfire, if those includes blacked out calendar jobs, and other type of execution that were not triggered because other reasons, e.g. quartz thread pool full, etc.

## URL
https://docs.rundeck.com/docs/manual/schedules/missedjobfires.html#missed-job-fires-enterprise-only

**Comment by Khelben-Arunsun** [comment]
Misfires show when scheduling is turned off for a job, while execution is enabled in 3.4.3. 
I would like to look at a jobs executions with the API, find the misfires I want, then run them as the business needs. 

POST /api/14/job/[ID]/schedule/disable

I need to leave it in the Disabled schedule state, have it misfire as executions are enabled.
Then make a call 
GET /api/11/job/[ID]/executions?status=missed

Then run the Jobs that were missed. 

With the flexibility of the API we can handle many corner cases in this manner.

**Comment by fdevans** [comment]
Please submit feature requests on the main `rundeck/rundeck` repository or through your CSM for Enterprise asks.  This repo is for documentation requests.
