### ISSUE TITLE
Please clarify if the minimum memory requirement is on machine or JVM

### ISSUE THREAD

**Issue by jgarces-pd** [rundeck/docs#925]
**Describe the bug**
Please clarify if the minimum memory requirement is on machine or JVM

<img width="253" alt="Screen Shot 2022-02-09 at 9 44 46 AM" src="https://user-images.githubusercontent.com/74255967/153203660-fbdad086-1cbf-41f6-902d-6bad0b12024c.png">

**Source page**
https://docs.rundeck.com/docs/administration/install/system-requirements.html

**Comment by jtobard** [comment]
closed here https://github.com/rundeck/docs/pull/947
