### ISSUE TITLE
Missing information about Pro version of the S3 log storage plugin

### ISSUE THREAD

**Issue by lcanavosio** [rundeck/docs#940]
**Describe the bug**
In this section of the documentation, there is no reference about the Pro version of the S3 log storage plugin, which supports checkpoints while writing the data.
_rundeck.execution.logs.fileStoragePlugin=com.rundeck.rundeckpro.amazon-s3_

**Source page**
https://docs.rundeck.com/docs/administration/cluster/logstore/s3.html#s3-log-storage-plugin

**Comment by fdevans** [comment]
fixed in #991
