### ISSUE TITLE
Release pages - Complete information needs to be added

### ISSUE THREAD

**Issue by afarias74** [rundeck/docs#949]
Hi team. This is an enhancement request for Rundeck Documentation. The customer is requesting this image:

 
<img width="835" alt="fix_your_release_pages" src="https://user-images.githubusercontent.com/100425466/161280246-9cc16c3a-02b7-4eab-8f66-bd4244cd7456.png">

needs to be in all our releases, not just the point-zero release’s page. The customer has explained that if he wants to update from a prior version to the current stable, he shouldn’t be expected to look at the earliest release for notes.

In addition, it would be great if you can add a tip/warning with the recommendation for users not to perform upgrades from more than two prior versions because that could cause unexpected errors. Thanks.

**Source page**
 (https://docs.rundeck.com/docs/history/3_4_x/version-3.4.0.html#overview)

**Comment by fdevans** [comment]
We can consider some standard text.  All of this is covered on our Upgrading pages here https://docs.rundeck.com/docs/upgrading/
