### ISSUE TITLE
Missing information about the rundeckpro properties of the Azure Log Storage Plugin

### ISSUE THREAD

**Issue by gian4820** [rundeck/docs#955]
**Describe the bug**
There is no documentation about the rundeckpro, properties of the Azure Log Storage Plugin. It's only available the OSS properties. 
Here is a screenshot of the rundeckpro properties that are listed in the information of the plugin in Rundeck GUI.
![azure_plugin_rundeckpro](https://user-images.githubusercontent.com/48934140/163890975-d6d2e546-020e-4180-b308-d8a097c14a1e.png)

**Source page**
[](https://docs.rundeck.com/docs/administration/cluster/logstore/azure.html)

**Comment by fdevans** [comment]
fixed in #991
